version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-web-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ji9zid9t79g"
s3_prefix = "sam-web-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
